server:
  port: 8080

spring:
  application:
    name: msgateway
  cloud:
    gateway:
      routes:

        # Main service routes - JWT will be passed by client and validated by JwtAuthenticationFilter
        - id: profile-service
          uri: http://msprofile:8081
          predicates:
            - Path=/api/v1/profiles/**

        - id: account-service
          uri: http://msaccount:8082
          predicates:
            - Path=/api/v1/accounts/**

        - id: payment-service
          uri: http://mspayment:8083
          predicates:
            - Path=/api/v1/payments/**

        - id: events-service
          uri: http://msevents:8084
          predicates:
            - Path=/api/v1/events/**

        # Swagger API Docs through gateway
        - id: profile-swagger
          uri: http://msprofile:8081
          predicates:
            - Path=/msprofile/swagger-ui.html
          filters:
            - RewritePath=/msprofile/swagger-ui.html, /swagger-ui/index.html

        - id: account-swagger
          uri: http://msaccount:8082
          predicates:
            - Path=/msaccount/swagger-ui.html
          filters:
            - RewritePath=/msaccount/swagger-ui.html, /swagger-ui/index.html

        - id: payment-swagger
          uri: http://mspayment:8083
          predicates:
            - Path=/mspayment/swagger-ui.html
          filters:
            - RewritePath=/mspayment/swagger-ui.html, /swagger-ui/index.html

        - id: events-swagger
          uri: http://msevents:8084
          predicates:
            - Path=/msevents/swagger-ui.html
          filters:
            - RewritePath=/msevents/swagger-ui.html, /swagger-ui/index.html

        - id: profile-api-docs
          uri: http://msprofile:8081
          predicates:
            - Path=/msprofile/v3/api-docs
          filters:
            - RewritePath=/msprofile/v3/api-docs, /v3/api-docs

        - id: account-api-docs
          uri: http://msaccount:8082
          predicates:
            - Path=/msaccount/v3/api-docs
          filters:
            - RewritePath=/msaccount/v3/api-docs, /v3/api-docs

        - id: payment-api-docs
          uri: http://mspayment:8083
          predicates:
            - Path=/mspayment/v3/api-docs
          filters:
            - RewritePath=/mspayment/v3/api-docs, /v3/api-docs

        - id: events-api-docs
          uri: http://msevents:8084
          predicates:
            - Path=/msevents/v3/api-docs
          filters:
            - RewritePath=/msevents/v3/api-docs, /v3/api-docs



springdoc:
  swagger-ui:
    urls:
      - name: msprofile
        url: /msprofile/v3/api-docs
      - name: msaccount
        url: /msaccount/v3/api-docs
      - name: mspayment
        url: /mspayment/v3/api-docs
      - name: msevents
        url: /msevents/v3/api-docs

app:
  auth-config:
    username: "admin"
    password: "5$kb)N>G1%oG58z"
    jwt-secret: "fnztEskaI5F0PYO9BU/HkQbzCjxABJsODPAb6d7x9nM="
    jwt-expiration-ms: 3600000 # 1 hour in milliseconds
