# ========================
# Server & App Metadata
# ========================
server.port=8084
spring.application.name=msevent

# ========================
# RabbitMQ Configuration
# ========================
spring.rabbitmq.host=rabbit
spring.rabbitmq.port=5672
spring.rabbitmq.username=user
spring.rabbitmq.password=password


# ========================
# Optional: Logging
# ========================
logging.level.io.r2dbc.postgresql=INFO
logging.level.org.springframework.data.r2dbc=DEBUG


# ========================
# Response Configuration
# ========================
app.response-config.success-response-code=0
app.response-config.success-response-message=Request successful
app.response-config.success-customer-message=Request Executed Successfully
app.response-config.failed-response-code=1
app.response-config.failed-response-message=Request failed
app.response-config.failed-customer-message=Request Execution Failed
app.response-config.error-response-code=2
app.response-config.error-response-message=An error occurred while processing your request
app.response-config.error-customer-message=An error occurred while processing your request
app.response-config.customer-exists-response-message=Customer already exists
app.response-config.customer-exists-customer-message=Customer already exists with the given Email
app.response-config.invalid-credentials-response-message=Invalid credentials
app.response-config.invalid-credentials-customer-message=Invalid Email or Password. PLease check and try again
app.response-config.customer-not-found-customer-message=Account with the given email not found
app.response-config.customer-not-found-response-message=Account not found

# ========================
# Rabbit Configuration
# ========================
app.response-config.exchange=my-exchange
app.response-config.routing-key=my-routing-key
app.response-config.queue=my-queue


